<a href="https://colab.research.google.com/github/RamosJarren/58013-LinearAlgebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1. Consider the four matrices, (20 points each)

a. AB

b. D + D

c. 2C

In [9]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
D = np.array([[1, 2], [3, 4]])

print("a. A * B\n", np.dot(A, B))
print("b. D + D\n", np.add(D, D))
print("c. 2C\n", 2 * C)

a. A * B
 [[22 28]
 [49 64]]
b. D + D
 [[2 4]
 [6 8]]
c. 2C
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Problem 2. Find the cross-product of matrices, A = [2,7,4] and

B = [3,9,8]. Show your solutions using Python program . (40 points)

In [10]:
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

print("d. A x B\n", np.cross(A, B))

d. A x B
 [20 -4 -3]


A = [2, 7, 4]   B = [3, 9, 8]

Ax = 2, Ay = 7, Az = 4

Bx = 7, By = 9, Bz = 8

x = (7 * 8) - (4 * 9) = 56 - 36 = 20

y = (4 * 3) - (2 * 8) = 12 - 16 = -4

x = (2 * 9) - (7 * 3) = 18 - 21 = -3

[20, -4, -3]