<a href="https://colab.research.google.com/github/RamosJarren/58013-LinearAlgebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [3]:
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than (3,3). In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [26]:
#Commutative
C = np.array([
    [1,0,7],
    [3,6,1],
    [9,0,3]
])
D = np.array([
    [3,1,9],
    [1,2,1],
    [6,3,7]
])
print(np.dot(C,D))
print(np.dot(D,C))

[[ 45  22  58]
 [ 21  18  40]
 [ 45  18 102]]
[[87  6 49]
 [16 12 12]
 [78 18 66]]


In [27]:
#Associative
E = np.array([
    [1,0,6],
    [1,2,4],
    [9,4,8]
])
F = np.array([
    [6,2,0],
    [8,6,2],
    [3,9,2]
])
G = np.array([
    [2,4,8],
    [3,2,9],
    [8,9,1]
])
print(np.dot(E, np.dot(F,G)))
print(np.dot(np.dot(E,F), G))

[[ 312  316  708]
 [ 314  344  734]
 [ 754  884 1930]]
[[ 312  316  708]
 [ 314  344  734]
 [ 754  884 1930]]


In [25]:
#Distributive
H = np.array([
    [6,0,6],
    [8,6,7],
    [0,8,4]
])
I = np.array([
    [5,8,9],
    [1,6,1],
    [8,7,5]
])
J = np.array([
    [2,4,2],
    [4,8,1],
    [8,3,6]
])
print(np.add(H, np.dot(I,J)))
print(np.add(np.dot(H,I), J))

[[120 111  78]
 [ 42  61  21]
 [ 84 111  57]]
[[ 80  94  86]
 [106 157 114]
 [ 48  79  34]]


In [29]:
#Identity
K = np.array([
    [2,5,6],
    [3,0,6],
    [8,6,3]
])
L = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])
print(np.dot(K,L))

[[2 5 6]
 [3 0 6]
 [8 6 3]]


In [30]:
#Zero
M = np.array([
    [2,5,6],
    [3,0,6],
    [8,6,3]
])
N = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]
])
print(np.dot(M,N))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [31]:
#Dimension
O = np.array([
    [1,9,6],
    [5,3,4]
])
P = np.array([
    [1,3],
    [3,2],
    [9,7]
])
print(np.dot(O,P))
print(np.dot(P,O))

[[82 63]
 [50 49]]
[[ 16  18  18]
 [ 13  33  26]
 [ 44 102  82]]
