<a href="https://colab.research.google.com/github/RamosJarren/58013-LinearAlgebra/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape)
print(Y)
print(Y.shape)

[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


So let's start off with an easy one. Let's say you have a bakery and you are purchasing supplies consisting of flour, yeast, and eggs from your supplier. For month 1 you bought a bakery promo that consists of 30 sacks of flour, 10 packs of yeast, and 120 eggs and you are charged for 12,500 pesos. For month two you bought a different bakery promo that consists of 40 sacks of flour, 20 packs of yeast, and 200 eggs then you are charged with 18,000 pesos. And then for month three you bought yet a different bakery promo that consists of 50 sacks of flour, 40 packs of yeast, and 360 eggs for 25,700 pesos. Now you are wondering if the promos are more cost-effective compared to buying them as a regular buyer, what could be the price of the flour per sack, yeast per pack, and one piece of egg?

	Create a python program to solve for the price of flour per sack, yeast per pack, and one piece of egg.


In [8]:
import numpy as np

X = np.array([
    [30, 10, 120],
    [40, 20, 200],
    [50, 40, 360]
], dtype=float)

Y = np.array([
    [12500],
    [18000],
    [25700]
], dtype=float)

invertX = np.linalg.inv(X)
result = np.dot(invertX, Y)

flour = result[0][0]
yeast = result[1][0]
egg = result[2][0]

print("Price of Flour per Sack: ₱", flour)
print("Price of Yeast per Sack: ₱", yeast)
print("Price of One Egg: ₱", egg)


Price of Flour per Sack: ₱ 329.99999999999864
Price of Yeast per Sack: ₱ 139.99999999999844
Price of One Egg: ₱ 10.000000000000059
