<a href="https://colab.research.google.com/github/RamosJarren/58013-LinearAlgebra/blob/main/Vector_Spaces_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix Array

In [4]:
import numpy as np

A = np.array([4, 3])
B = np.array([2, -5])

print("Vector A is", A)
print("Vector B is", B)

Vector A is [4 3]
Vector B is [ 2 -5]


Column Vector

In [22]:
import numpy as py

ball1 = np.array([[1], [2], [3]])
print(ball1)

[[1]
 [2]
 [3]]


Shape of the Matrix

In [32]:
import numpy as np

ball1 = np.array([1, 2, 3])
ball2 = np.array([0, 1, -1])
print(ball1)
print(ball2)
print(np.shape([ball1, ball2]))

[1 2 3]
[ 0  1 -1]
(2, 3)


Vector Addition

In [34]:
import numpy as np

A = np.array([4, 3])
B = np.array([2, -5])
print(np.add(A, B))
print(np.subtract(A, B))

[ 6 -2]
[2 8]


Scalar

In [38]:
import numpy as np

A = np.array([4, 3])
B = np.array([1, 5, 8, 9])
C = 5 * B
print(C)

D = np.array([2])
print(A * D)

[ 5 25 40 45]
[8 6]


Vector Multiplication

In [45]:
import numpy as np

A = np.array([2, 3])
B = np.array([1, 7])
print(np.dot(A, B))
print(np.cross(A, B))

C = np.array([4, 3])
D = np.array([[2], [-5]])
print(np.dot(C, D))


23
11
[-7]


Identity Matrix

In [49]:
import numpy as np

print(np.eye(3, 3))
print(np.eye(3, k = -1))
print(np.eye(3, k = 1))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


Zero Matrix

In [50]:
import numpy as np

print(np.zeros((5, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Full Matrix

In [54]:
import numpy as np

print(np.full([4, 4], 4))

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


Transpose Matrix

In [67]:
import numpy as np

print(np.transpose(np.array([[4, 3, 8, 9], [2, 7, 1, 0]])))

[[4 2]
 [3 7]
 [8 1]
 [9 0]]
